services:
  postgres-meri:
    image: pgvector/pgvector:pg17  # PostgreSQL with pgvector extension
    container_name: postgres-meri
    environment:
      POSTGRES_USER: ${SQL_USER:-user}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-password}
      POSTGRES_DB: ${SQL_DATABASE:-meri}
    ports:
      - ${SQL_PORT:-55432}:5432
