class StatementNotFoundException(Exception):
    def __init__(self, message: str = 'Statement not found') -> None: ...

class StatementConstraintException(Exception):
    def __init__(self, message: str = 'Statement constraint exception') -> None: ...
