name: On commit on main branch

on:
  push:
    branches:
      - main

jobs:
  check-python-code:
    name: Check python code
    uses: gueriboutmathieu/python_utils/.github/workflows/callable__check_python_code.yaml@1.0.16
    secrets: inherit
    with:
      env-vars: '{"VECTOR_DIMENSIONS": "1536", "VECTOR_DATABASE_FILE_PATH": "vector_database.bin"}'

  validate-alembic-migrations:
    name: Check python code
    uses: gueriboutmathieu/python_utils/.github/workflows/callable__validate_alembic_migrations.yaml@1.0.16
    needs: check-python-code
    secrets: inherit
    with:
      docker_image: "pgvector/pgvector:pg17"
      env-vars: '{"VECTOR_DIMENSIONS": "1536", "VECTOR_DATABASE_FILE_PATH": "vector_database.bin"}'

  build-and-release:
    name: Build and release
    uses: gueriboutmathieu/python_utils/.github/workflows/callable__build_and_release.yaml@1.0.16
    needs: validate-alembic-migrations
    secrets: inherit
    with:
      package-name: "meri"
