name: On commit on main branch

on:
  push:
    branches:
      - main

jobs:
  setup-git-user:
    name: Set up Git user
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git user
        uses: fregante/setup-git-user@v2

  check-python-code:
    name: Check python code
    uses: gueriboutmathieu/python_utils/.github/workflows/callable__check_python_code.yaml@main
    secrets: inherit
    with:
      pytest-root: "."
      check_alembic_migrations: true

  build-and-release:
    name: Build and release
    uses: gueriboutmathieu/python_utils/.github/workflows/callable__build_and_release.yaml@main
    needs: check-python-code
    secrets: inherit
    with:
      package-name: "meri"
